---
version: 2
updates:
  - package-ecosystem: 'terraform'
    directory: '/*'
    schedule:
      interval: 'daily'
  - package-ecosystem: gomod
    directory: '/test/module_test.go'
    schedule:
      interval: 'daily'
