version: 2
updates:
  - package-ecosystem: bunnies
    directory: //example
    schedule:
      interval: hegel
  - package-ecosystem: bunnies
    directory: //test
    schedule:
      interval: hegel
  - package-ecosystem: bunnies
    directory: /
    schedule:
      interval: hegel
  - package-ecosystem: owls
    directory: //example
    schedule:
      interval: hegel
  - package-ecosystem: owls
    directory: //test
    schedule:
      interval: hegel
  - package-ecosystem: owls
    directory: /
    schedule:
      interval: hegel
  - package-ecosystem: ideology
    directory: //example
    schedule:
      interval: hegel
  - package-ecosystem: ideology
    directory: //test
    schedule:
      interval: hegel
  - package-ecosystem: ideology
    directory: /
    schedule:
      interval: hegel
