---
version: 2
updates:
  - package-ecosystem: 'terraform'
    directory: '{/*.tf,/*.tfvars,!/example/*}'
    schedule:
      interval: 'daily'
  - package-ecosystem: gomod
    directory: '/test/*'
    schedule:
      interval: 'daily'
