version: 2
updates:
  - package-ecosystem: terraform
    directory: //example
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: //test
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: //example
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: //test
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
