name: Generate dependabot.yml

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        
      - name: Generate Dependabot Glob
        uses: Makeshift/generate-dependabot-glob-action@v1.2.1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        env:
            PRNUM: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge PR
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }}