---
name: Pull Request for Slavoj Zizek

on:
  push:
    paths:
      - ".github/dependabot.yml"

jobs:

  slavojpr:
    name: Slavojure
    uses: danny-molnar/blastarcade/.github/workflows/composite_action.yml@main