---
name: Retrigger Workflow Demo

on:
  pull_request:
    types:
      - synchronize
  workflow_dispatch:

jobs:
  retrigger:
    name: Retrigger wf
    uses: danny-molnar/blastarcade/.github/workflows/retriggered_wf.yml@main